server:
  port: ${PALETTE_SERVER_PORT}
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  jackson:
    default-property-inclusion: ALWAYS

  datasource:
    url: ${PALETTE_SERVER_DB_URL}
    driver-class-name: ${PALETTE_SERVER_DB_DRIVER}
    username: ${PALETTE_SERVER_DB_USER}
    password: ${PALETTE_SERVER_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath*:db/data.sql
      mode: always

  data:
    mongodb:
      host: ${PALETTE_SERVER_MONGODB_HOST}
      port: ${PALETTE_SERVER_MONGODB_PORT}
      database: ${PALETTE_SERVER_MONGODB}

  servlet:
    multipart:
      max-file-size: 5MB